[MongoDB ] MongoDB use case
sylabs/examples pull request #16
Opened 2018-10-11 21:11 UTC by devprincess

Contains:
- Definition file
- Readme file description: Describing all the sections in the def file and the way to run it and use it.

2018-10-12 20:06 UTC, GodloveD submitted a review, later dismissed

2018-10-12 20:06 UTC, GodloveD commented on database/mongodb/README.md
> +```
I'm not really sure the `echo | tee` command is necessary to demonstrate what version of MongoDB you are using.

2018-10-12 20:06 UTC, GodloveD commented on database/mongodb/README.md
> +
Something like:

You can obtain the definition file with:
```
wget URI/to/raw/def
```

2018-10-12 20:06 UTC, GodloveD commented on database/mongodb/README.md
> +
Could also be good way to demonstrate the `$SINGULARITYENV_*` variables later on.  So that a user can change their hostname and port at runtime.

2018-10-12 20:06 UTC, GodloveD commented on database/mongodb/README.md
> +After exporting them, the `%post` section contains the installation of all the needed dependencies for MongoDB to run correctly. Also the folders in which the data from the database will be saved are
missed talking about the `%help` section

2018-10-12 20:06 UTC, GodloveD commented on database/mongodb/README.md
> +```
This command returned an error for me:
```
$ sudo singularity run mongodb.sif
2018-10-12T12:19:41.345-0400 I CONTROL  [main] Automatically disabling TLS 1.0, to force-enable TLS 1.0 specify --sslDisabledProtocols 'none'
2018-10-12T12:19:41.368-0400 I CONTROL  [initandlisten] MongoDB starting : pid=119371 port=27017 dbpath=/data/db 64-bit host=ubuntu
2018-10-12T12:19:41.368-0400 I CONTROL  [initandlisten] db version v4.0.3
2018-10-12T12:19:41.368-0400 I CONTROL  [initandlisten] git version: 7ea530946fa7880364d88c8d8b6026bbc9ffa48c
2018-10-12T12:19:41.368-0400 I CONTROL  [initandlisten] OpenSSL version: OpenSSL 1.1.0f  25 May 2017
2018-10-12T12:19:41.368-0400 I CONTROL  [initandlisten] allocator: tcmalloc
2018-10-12T12:19:41.368-0400 I CONTROL  [initandlisten] modules: none
2018-10-12T12:19:41.368-0400 I CONTROL  [initandlisten] build environment:
2018-10-12T12:19:41.368-0400 I CONTROL  [initandlisten]     distmod: debian92
2018-10-12T12:19:41.368-0400 I CONTROL  [initandlisten]     distarch: x86_64
2018-10-12T12:19:41.368-0400 I CONTROL  [initandlisten]     target_arch: x86_64
2018-10-12T12:19:41.368-0400 I CONTROL  [initandlisten] options: { repair: true }
2018-10-12T12:19:41.384-0400 I STORAGE  [initandlisten] exception in initAndListen: DBPathInUse: Unable to create/open the lock file: /data/db/mongod.lock (Unknown error). Ensure the user executing mongod is the owner of the lock file and has the appropriate permissions. Also make sure that another mongod instance is not already running on the /data/db directory, terminating
2018-10-12T12:19:41.384-0400 I CONTROL  [initandlisten] now exiting
2018-10-12T12:19:41.384-0400 I CONTROL  [initandlisten] shutting down with code:100
2018-10-12T12:19:41.416-0400 I CONTROL  [main] Automatically disabling TLS 1.0, to force-enable TLS 1.0 specify --sslDisabledProtocols 'none'
2018-10-12T12:19:41.422-0400 I CONTROL  [initandlisten] MongoDB starting : pid=119374 port=27017 dbpath=/data/db 64-bit host=ubuntu
2018-10-12T12:19:41.422-0400 I CONTROL  [initandlisten] db version v4.0.3
2018-10-12T12:19:41.422-0400 I CONTROL  [initandlisten] git version: 7ea530946fa7880364d88c8d8b6026bbc9ffa48c
2018-10-12T12:19:41.422-0400 I CONTROL  [initandlisten] OpenSSL version: OpenSSL 1.1.0f  25 May 2017
2018-10-12T12:19:41.422-0400 I CONTROL  [initandlisten] allocator: tcmalloc
2018-10-12T12:19:41.422-0400 I CONTROL  [initandlisten] modules: none
2018-10-12T12:19:41.422-0400 I CONTROL  [initandlisten] build environment:
2018-10-12T12:19:41.422-0400 I CONTROL  [initandlisten]     distmod: debian92
2018-10-12T12:19:41.422-0400 I CONTROL  [initandlisten]     distarch: x86_64
2018-10-12T12:19:41.422-0400 I CONTROL  [initandlisten]     target_arch: x86_64
2018-10-12T12:19:41.422-0400 I CONTROL  [initandlisten] options: {}
2018-10-12T12:19:41.422-0400 I STORAGE  [initandlisten] exception in initAndListen: DBPathInUse: Unable to create/open the lock file: /data/db/mongod.lock (Unknown error). Ensure the user executing mongod is the owner of the lock file and has the appropriate permissions. Also make sure that another mongod instance is not already running on the /data/db directory, terminating
2018-10-12T12:19:41.422-0400 I NETWORK  [initandlisten] shutdown: going to close listening sockets...
2018-10-12T12:19:41.422-0400 I NETWORK  [initandlisten] removing socket file: /tmp/mongodb-27017.sock
2018-10-12T12:19:41.423-0400 I CONTROL  [initandlisten] now exiting
2018-10-12T12:19:41.423-0400 I CONTROL  [initandlisten] shutting down with code:100
MongoDB shell version v4.0.3
connecting to: mongodb://127.0.0.1:27017/
2018-10-12T12:19:41.649-0400 E QUERY    [js] Error: couldn't connect to server 127.0.0.1:27017, connection attempt failed: SocketException: Error connecting to 127.0.0.1:27017 :: caused by :: Connection refused :
connect@src/mongo/shell/mongo.js:257:13
@(connect):1:6
exception: connect failed
```

2018-10-12 20:06 UTC, GodloveD commented on database/mongodb/mongodb.def
> +%runscript
Better to do an instance for this I think

2018-10-12 20:11 UTC, jmstover commented on database/mongodb/mongodb.def
> +	chmod -R 777 /data/db
This is creating a `/data/db` in the container. This will be read-only in a SIF file.

2018-10-12 23:03 UTC, devprincess commented
@GodloveD @jmstover added corrections, let me know if this looks good for you, thanks!

2018-10-16 17:38 UTC, jmstover requested changes

2018-10-16 17:38 UTC, jmstover commented on database/mongodb/README.md
> +$ sudo singularity shell mongodb.sif
This isn't bind mounting in a directory that can be written to within the container from this command.

2018-10-16 18:16 UTC, devprincess commented
@jmstover @GodloveD setting it up now with the exported variable `SINGULARITY_BINDPATH` as suggested, lmk thanks :+1:

2018-10-16 18:17 UTC, jmstover approved these changes

2018-10-17 17:47 UTC, merged