[RabbitMQ] RabbitMQ use case
sylabs/examples pull request #40
Opened 2018-11-14 18:58 UTC by devprincess

:rabbit:

Contains: 
- def file
- Readme file
- send.py (sending python program to test the RabbitMQ protocol)
- receive.py (receiving python program to test the RabbitMQ protocol)
- a pic of the queue to explain the producer/consumer protocol (used on the readme of course)

2018-11-14 19:28 UTC, WestleyK commented on message-broker/rabbitmq/README.md
> +```
I would add:
```
$ cd ~/rabbitmq/
```

I think it would be easier for the users to follow.

2018-11-14 19:31 UTC, WestleyK commented on message-broker/rabbitmq/README.md
> +$ mkdir -p ~/rabbitmq/var/lib/rabbitmq
Why no just one command:
```
$ mkdir -p rabbitmq/var/{lib/rabbitmq,log}
```

And yes, this command works, I just tested it.

2018-11-14 19:32 UTC, WestleyK commented on message-broker/rabbitmq/README.md
> +$ mkdir -p ~/rabbitmq/var/lib/rabbitmq
Its easier to copy-past one command.

2018-11-14 19:37 UTC, WestleyK commented on message-broker/rabbitmq/README.md
> +$ mkdir -p ~/rabbitmq/var/lib/rabbitmq
Or if you `cd ~/rabbitmq/` to that directory:

```
$ mkdir -p var/{lib/rabbitmq,log}
```

2018-11-14 19:39 UTC, WestleyK commented on message-broker/rabbitmq/README.md
> +$ singularity pull library://sylabs/examples/rabbitmq:latest
You can this instead:

```
$ singularity pull rabbitmq.sif library://sylabs/examples/rabbitmq:latest
```

Sorry, my bad I did't know this before.

2018-11-14 19:39 UTC, WestleyK commented on message-broker/rabbitmq/README.md
> +```
Then you don't need the `rename the container...`

2018-11-28 17:20 UTC, WestleyK commented on message-broker/rabbitmq/README.md
> +             |--log
Maybe replace some of the '|' with '`', like this:

```
~/rabbitmq
        `---var
             |--lib
             |    `--rabbitmq
             `--log
```

2018-11-28 18:38 UTC, WestleyK commented on message-broker/rabbitmq/README.md
> +## RabbitMQ
I would remove one of the `#`, so:

```
 # RabbitMQ 
```

2018-11-30 22:25 UTC, WestleyK commented on message-broker/rabbitmq/README.md
> + ```
I don't see why the `singularity search ...` needs to be here. Maybe make a title for it, like:

```
#### Searching for the container:
...
```

Or you could just delete this part.

2018-11-30 22:30 UTC, WestleyK commented on message-broker/rabbitmq/README.md
> +
Maybe offer to pull the container:

```
$ singularity pull library://sylabs/examples/rabbitmq:latest
```
I'll push & sign the container when your ready.

2018-11-30 22:31 UTC, WestleyK commented on message-broker/rabbitmq/README.md
> +
Opps! nevermined!

2018-11-30 22:32 UTC, WestleyK commented on message-broker/rabbitmq/README.md
> +
I forget you had a pull command below. Sorry :/

2018-12-11 18:23 UTC, WestleyK reviewed
It just needs this link added to the example map, Like this:

```
Machine Learning
  -      Caffe
  -      Detectron
  -      H2o4gpu
  -      Horovod

Message Broker
  -      RabbitMQ
```

After this, I think its ready :+1:

2018-12-12 19:01 UTC, WestleyK commented on message-broker/rabbitmq/README.md
> +```
I would add `/` after each directory, like:

```
~/rabbitmq/
       `---var/
              |--lib/
              |   `--rabbitmq/
              `--log/
```

<br>

Last change :+1:

2018-12-12 19:03 UTC, WestleyK approved these changes
Looks good to me!  :)

2018-12-12 20:14 UTC, GodloveD requested changes
Asking for a few changes.  After they are done feel free to merge. Thanks @devprincess!

2018-12-12 20:14 UTC, GodloveD commented on message-broker/rabbitmq/README.md
> +$ sudo singularity instance start --bind ~/rabbitmq/var/lib:/var/lib,~/rabbitmq/var/lib/rabbitmq:/var/lib/rabbitmq,~/rabbitmq/var/log:/var/log rabbitmq.sif
This command results in an error because the instance is not named (instance start requires 2 inputs).

2018-12-12 20:14 UTC, GodloveD commented on message-broker/rabbitmq/README.md
> +Then, you will see the instance started with the command line output similar to this one:
I don't actually see this output.  I just see

```
vagrant@ubuntu-bionic:~/rabbitmq$ sudo singularity instance start --bind ~/rabbitmq/var/lib:/var/lib,~/rabbitmq/var/lib/rabbitmq:/var/lib/rabbitmq,~/rabbitmq/var/log:/var/log rabbitmq.sif rabbitmq
INFO:    instance started successfully
```

2018-12-12 20:14 UTC, GodloveD commented on message-broker/rabbitmq/receive.py
> +#!/usr/bin/env python
Needs to be `#!/usr/bin/env python3`.  Then you can dispense with the `python3` directive in the README.md.  This tripped me up at first b/c I missed the `python3` command.  Guess I thought it was just part of the prompt.

2018-12-12 20:14 UTC, GodloveD commented on message-broker/rabbitmq/send.py
> +#!/usr/bin/env python
Needs to be `#!/usr/bin/env python3`.

2018-12-12 20:14 UTC, GodloveD commented on message-broker/rabbitmq/README.md
> +#!/usr/bin/env python
change to `python3`

2018-12-12 20:14 UTC, GodloveD commented on message-broker/rabbitmq/README.md
> +We will see an explanation of this code below when we run the example.
make the scripts executable with `chmod 755` or similar.

2018-12-13 20:50 UTC, jmstover approved these changes

2018-12-18 15:56 UTC, GodloveD approved these changes

2018-12-18 15:56 UTC, merged