[Memcached] Memcached use case
sylabs/examples pull request #43
Opened 2018-11-20 16:51 UTC by devprincess

Simple use case on how to create a Memcached Singularity container, tested with telnet

2018-11-20 17:06 UTC, WestleyK commented on caching-system/memcached/README.md
> +## Memcached
I would remove one of the `#`, to make the title look even bigger.

2018-11-20 17:08 UTC, WestleyK commented on caching-system/memcached/README.md
> +   1. Go to : https://cloud.sylabs.io/
It seems like theres a extra space here:

```
   1. Go to : https://cloud.sylabs.io/
 ^
```

2018-11-20 17:10 UTC, WestleyK commented on caching-system/memcached/memcached.def
> +  apt-get update
Maybe add `-y` to `apt-get update`, so:
```
apt-get -y update
```

2018-11-20 17:11 UTC, WestleyK commented on caching-system/memcached/memcached.def
> +  #Listen on TCP port 11211 and UDP port 11111 as a daemon process
I like to put a space after the `#`, Its a little easier to read, I think
```
# Listen on TCP port 11211 and UDP port 11111 as a daemon process
 ^
 add the space here
```

2018-11-30 22:33 UTC, WestleyK commented on caching-system/memcached/README.md
> + $ singularity pull memcached.sif library://sylabs/examples/memcached
I would add a `:latest` tag after the pull command.

2018-11-30 22:36 UTC, WestleyK commented on caching-system/memcached/memcached.def
> +
You could add a URL for the github page, something like:

```
for more info/tutorial, visit: https://github.com/sylabs/examples/tree/master/caching-system/memcached
```

2018-12-01 05:42 UTC, WestleyK commented on caching-system/memcached/README.md
> +After this, inside the `~/memcached` folder we will build our `Memcached` container. To do so:
Why is "`Memcached`" capitalized, and should it be: `mencached.sif`?

2018-12-04 20:16 UTC, WestleyK reviewed
I think `memcached` should be added to the example map. Otherwise, it looks good! :+1:

2018-12-13 20:52 UTC, jmstover requested changes

2018-12-13 20:52 UTC, jmstover commented on caching-system/memcached/memcached.def
> +From: ubuntu:18.04
Using Ubuntu 18.x this will not run on RHEL 6. Do we want to put in a comment about that restriction?

2019-07-19 23:45 UTC, closed without merging