Packaging section and FPM example
sylabs/examples pull request #57
Opened 2019-01-25 19:54 UTC by jmdf

I've been using a singularity container with [FPM](https://github.com/jordansissel/fpm) installed to package everything I need, across different systems/environments

It works pretty well and I think it's a good example to have here.

2019-02-01 18:47 UTC, GodloveD requested changes
Heya @jmdf !  Thanks so much for the contribution.  Sorry it took a little time to see and review.  Can you add this directory and file to the top level README.md so that it will be reflected in the map there?  Other than that I'm and the one other comment about simg to sif I'm happy to approve and merge.

2019-02-01 18:47 UTC, GodloveD commented on packaging/fpm/README.md
> +`sudo singularity build fpm.simg fpm.def`
can you change `fpm.simg` to `fpm.sif` throughout to reflect the new SIF format in 3.0?

2019-02-02 00:17 UTC, jmdf commented
Hey @GodloveD !
Files changed as requested and it's ready to be reviewed again.

Thanks for the input.

2019-02-04 15:36 UTC, GodloveD commented
Thanks @jmdf!  Looks good!

2019-02-04 15:36 UTC, GodloveD approved these changes

2019-02-04 15:37 UTC, merged